name: Publish NPM Package

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: https://registry.npmjs.org
          cache: 'npm'

      - name: NPM CI
        run: npm ci

      - name: Build Angular Library
        run: npm run build:ng

      - name: Publish NPM
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          cd ./dist/library
          npm version ${VERSION}
          npm publish --access=public
